name: NPM Audit Scan using Github Actions for NMP ASE CL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  npm-audit-scan-job:
    name: NPM Audit Scan ASE CL
    runs-on: ubuntu-latest
    steps:
      - name: Step1 Download the Source Code
        uses: actions/checkout@v4

      - name: Step2 Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.1'

      - name: Step3 Install Dependencies
        run: npm install

      - name: Step4 NPM Audit Scan and Generate Report in JSON Format
        run: npm audit --json > npm-audit-results.json
        
        continue-on-error: true

      - name: Step5 Upload NPM Audit Scan Report to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: pindakaas
          path: banana.json
          #curl -X POST -H "Content-Type: application/json" -d '{"key1": "value1", "key2": "value2"}' http://35.219.178.165:8880/callback
    
     # - uses: actions/checkout@master
      #- name: curl
       #   uses: curl@v1.0.2
        #with:
         # args: --upload-file curl -X POST -H "Content-Type: application/json" -d '{"key1": "value1", "key2": "value2"}'  http://35.219.137.114:8880/callback http://35.219.178.165:8880/callback
